version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-fpm-node
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo docker-php-ext-install zip
      # Composer
      - restore_cache:
          name: Restore composer cache
          keys:
            - composer-{{ checksum "composer.json" }}
            - composer-
      - run: composer install -n --prefer-dist
      - save_cache:
          name: Store composer cache
          key: composer-{{ checksum "composer.json" }}
          paths:
            - vendor
      - run: sudo composer update
      - run: ./vendor/bin/phpcs -n --standard=phpcs.xml
  # deploy:
  #   machine: true
  #   steps:
  #     - checkout
  #     - run:
  #         name: Build and push Docker image to Heroku
  #         command: |
  #           set -x
  #           sudo curl https://cli-assets.heroku.com/install.sh | sh
  #           HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
  #           HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a circle-ci-tutorial web
  #           HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a circle-ci-tutorial web
# workflows:
#   version: 2
#   build-and-deploy:
#     jobs:
#       - build
      # - deploy:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only: main
